version: "3.9"
services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: 
      MONGO_INITDB_ROOT_PASSWORD: 

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: 
      ME_CONFIG_MONGODB_ADMINPASSWORD: 
      ME_CONFIG_MONGODB_URL: 
  
  web:
    build: .
    environment:
      AWS_ACCESS_KEY_ID: 
      AWS_SECRET_ACCESS_KEY:
      COMPANY: 
      CONNECTIONSTRING: 
      COGNITO_IDENTITY_POOL_ID: 
      MODE: DEV
    ports:
      - "3000:3000"
    volumes:
      - .:/home/chappie
      - /home/chappie/node_modules
    depends_on: 
      - mongo